name: CI/CD with GitHub pages

on: 
  push: 
    branches:
      - master

jobs: 

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: HTML5Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: ./
      - name: Create artifacts
        uses: actions/upload-artifact@v2
        with:
          name: html-artifacts
          path: ./


  deploy:

    needs: build

    permissions:
      pages: write
      id-token: write

    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with: 
          path: '.'
      - name: Deploy to GH pages
        id: deployment
        uses: actions/deploy-pages@v2