name: CI/CD with GitHub pages

on: 
  push: 
    branches:
      - master

jobs: 

  deploy:

    permissions:
      pages: write
      id-token: write

    environment: 
      name: github-pages
      url: ${{ steps.pages.outputs_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pages
        uses: actions/configure-github-pages@v3
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with: 
          path: '.'
      - name: Deploy to GH pages
        id: deployment
        uses: actions/deploy-pages@v2