name: CI/CD with GitHub pages

on: 
  push: 
    branches:
      - master

jobs: 

  build:
    runs on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check HTML validity
        uses: actions/upload-artifact@v3
        with:
          path: "."
      - name: Create artifacts
        uses: actions/create-artifact@v2
        with:
          name: html
          path: "."


  deploy:

    permissions:
      pages: write
      id-token: write

    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with: 
          path: '.'
      - name: Deploy to GH pages
        id: deployment
        uses: actions/deploy-pages@v2